### PR TITLE
Remove `-w dupbuild` completely, always error on duplicate edges

### LINKED ISSUE #931: Turn duplicate rules for the same target into an error
If multiple build edges generate the same output, ninja currently warns with

```
ninja: warning: multiple rules generate $name. build will not be correct; continuing anyway
```

Internally, ninja just ignores all but the last rule. In practice, this usually happens if people accidentally repeat a rule in their meta-buildsystem. But for rules with multiple targets, ninja's current handling of this can lead to inconsistent build graphs that can lead to crashes (see e.g. #867). Also, some people mistake this diagnostic for a bug in ninja instead of a bug in their build files (e.g. #543 last comment). Arguably, ninja could try to check if the two rules are exactly the same and not complain in that case, but
1. That's something the generator could do
2. It's not always obvious – the commands could be `cd ../.. && foo/bar.sh` and `cd ../../.. && baz/foo/bar.sh`, or they could set slightly different env vars (which happen to not make a difference in practice, but ninja can't know that)

So this should be an error, not a warning. However, this is something that happens in practice every now and then (examples: http://reviews.llvm.org/D6166#109619 http://crbug.com/351052), so the rollout for this should look something like this:
1. [x] Add a flag to turn this warning into an error, but don't set it by default (`--dupeedge=[warn|error]`?), make a release with this. (Mention the flag name in the warning text.)
2. [x] File bugs with all known generators to reject duplicate rules for the same target (up to generators to allow this if the two rules effectively are the same – generators are in a better position to make that decision. If they opt to do that, they still should only write one of these rules). Wait for this to be implemented everywhere, and to make it into releases.
3. [x] Flip the flag default to error, but keep the flag around to switch back to warning, keep mentioning the flag in the error message, and in --help output. Make another release.
4. [x] Remove flag from error message and help output, but keep honoring it. Make another release.
5. [ ] Eventually, remove the flag.

Not sure if we ever actually want to do 5, but the rest all seem like Obviously Good steps.

### PR DESCRIPTION
**Pull request by jhasse**
Step 5, fixes #931.

### CODE REVIEW

File: src/manifest_parser_test.cc [hunk 1]
```diff
@@ -997,28 +970,26 @@ TEST_F(ParserTest, ImplicitOutputEmpty) {
...
-  Edge* edge = state.LookupNode("foo")->in_edge();
-  ASSERT_EQ(edge->outputs_.size(), 3);
-  EXPECT_FALSE(edge->is_implicit_out(0));
-  EXPECT_FALSE(edge->is_implicit_out(1));
-  EXPECT_TRUE(edge->is_implicit_out(2));
+"build foo baz | foo baq foo: cat bar\n";
+  ManifestParser parser(&state, &fs_);
+  string err;
+  EXPECT_FALSE(parser.ParseTest(kInput, &err));
+  EXPECT_EQ("input:4: multiple rules generate foo\n", err);
```
Comment (digit-google) [inline src/manifest_parser_test.cc:981]: This error message is now misleading, because in this case a single rule has multiple outputs. Would it be a good opportunity to change it to something like `foo is defined as an output multiple times` instead?

Comment (jhasse) [reply src/manifest_parser_test.cc]: Yes, good idea. See new commit :)
